-d G:\Nano_9K_HDMI\impl\gwsynthesis\Nano_9K_HDMI.vg
-p GW1NR-9C-QFN88P-6
-pn GW1NR-LV9QN88PC6/I5
-cst G:\Nano_9K_HDMI\src\Nano_9K_HDMI.cst
-cfg G:\Nano_9K_HDMI\impl\pnr\device.cfg
-sdc G:\Nano_9K_HDMI\src\Nano_9K_HDMI.sdc
-bit
-tr
-ph
-timing
-cst_error
-route_maxfan 23
